# Database setup

Reads a v2 JSON experiment config, loads it into a DuckDB database through the `deepecohab.utils.db` / `deepecohab.utils.loaders` domain layer, then extracts the experiment, cages, animals, and antenna-pair interpolation data back out.

In [1]:
from pathlib import Path

import polars as pl

from deepecohab.utils.domain import Cage
from deepecohab.utils.loaders import JsonConfigLoader
from deepecohab.utils.db import connect, DuckDBExperimentRepository

## Read the config

In [2]:
config_path = Path.home() / "Downloads" / "DeepEcoHAB_config.json"
loader = JsonConfigLoader(config_path)

experiment = loader.load_experiment(interpolate=True)
experiment

Experiment(name='DeepEcoHAB', start=datetime.datetime(2026, 6, 10, 11, 39, 24, 553118), end=None, light_start='07:00', dark_start='19:00', recording_timezone='Europe/Warsaw', animals={'EE1CEC1A': Animal(tag_no='EE1CEC1A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '6D68A819': Animal(tag_no='6D68A819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), 'DD43E61A': Animal(tag_no='DD43E61A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '3AFE9F1A': Animal(tag_no='3AFE9F1A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), 'D5969C1A': Animal(tag_no='D5969C1A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '0265E61A': Animal(tag_no='0265E61A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), 'F02AE61A': Animal(tag_no='F02AE61A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '12F5FF19': Animal(tag_no='12F5FF19', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '3AE5FF19': Animal(tag_no='3AE5FF19', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort2_implant_worked_03_06_2026'), 'C8E2FF19': Animal(tag_no='C8E2FF19', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort2_implant_worked_03_06_2026'), 'C046E61A': Animal(tag_no='C046E61A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort2_implant_worked_03_06_2026'), 'F5EFFF19': Animal(tag_no='F5EFFF19', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'F273A819': Animal(tag_no='F273A819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'D71EA819': Animal(tag_no='D71EA819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'E967A819': Animal(tag_no='E967A819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'E6A59C1A': Animal(tag_no='E6A59C1A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'A16CA819': Animal(tag_no='A16CA819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'F61EA819': Animal(tag_no='F61EA819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia')}, layout=Layout(cages={'cage_2': Cage(id='cage_2', cage_no=2, cage_type='Food'), 'cage_3': Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), 'cage_1': Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), 'cage_4': Cage(id='cage_4', cage_no=4, cage_type='Food')}, tunnels={'tunnel_1': Tunnel(id='tunnel_1', name='T1', endpoints=frozenset({'cage_1', 'cage_2'}), antennas={'cage_2': 1, 'cage_1': 0}, is_deadend=False), 'tunnel_2': Tunnel(id='tunnel_2', name='T2', endpoints=frozenset({'cage_3', 'cage_4'}), antennas={'cage_3': 5, 'cage_4': 4}, is_deadend=False), 'tunnel_3': Tunnel(id='tunnel_3', name='T3', endpoints=frozenset({'cage_2', 'cage_3'}), antennas={'cage_2': 7, 'cage_3': 6}, is_deadend=False), 'tunnel_4': Tunnel(id='tunnel_4', name='T4', endpoints=frozenset({'cage_1', 'cage_4'}), antennas={'cage_1': 8, 'cage_4': 9}, is_deadend=False)}, antennas={1: Antenna(id=1, tunnel_id='tunnel_1', cage_id='cage_2'), 0: Antenna(id=0, tunnel_id='tunnel_1', cage_id='cage_1'), 5: Antenna(id=5, tunnel_id='tunnel_2', cage_id='cage_3'), 4: Antenna(id=4, tunnel_id='tunnel_2', cage_id='cage_4'), 7: Antenna(id=7, tunnel_id='tunnel_3', cage_id='cage_2'), 6: Antenna(id=6, tunnel_id='tunnel_3', cage_id='cage_3'), 8: Antenna(id=8, tunnel_id='tunnel_4', cage_id='cage_1'), 9: Antenna(id=9, tunnel_id='tunnel_4', cage_id='cage_4')}, _pairs={(1, 0): Crossing(tunnel_id='tunnel_1', from_cage_id='cage_2', to_cage_id='cage_1'), (0, 1): Crossing(tunnel_id='tunnel_1', from_cage_id='cage_1', to_cage_id='cage_2'), (5, 4): Crossing(tunnel_id='tunnel_2', from_cage_id='cage_3', to_cage_id='cage_4'), (4, 5): Crossing(tunnel_id='tunnel_2', from_cage_id='cage_4', to_cage_id='cage_3'), (7, 6): Crossing(tunnel_id='tunnel_3', from_cage_id='cage_2', to_cage_id='cage_3'), (6, 7): Crossing(tunnel_id='tunnel_3', from_cage_id='cage_3', to_cage_id='cage_2'), (8, 9): Crossing(tunnel_id='tunnel_4', from_cage_id='cage_1', to_cage_id='cage_4'), (9, 8): Crossing(tunnel_id='tunnel_4', from_cage_id='cage_4', to_cage_id='cage_1'), (1, 1): Cage(id='cage_2', cage_no=2, cage_type='Food'), (7, 7): Cage(id='cage_2', cage_no=2, cage_type='Food'), (1, 7): Cage(id='cage_2', cage_no=2, cage_type='Food'), (7, 1): Cage(id='cage_2', cage_no=2, cage_type='Food'), (1, 6): Cage(id='cage_2', cage_no=2, cage_type='Food'), (6, 1): Cage(id='cage_2', cage_no=2, cage_type='Food'), (7, 0): Cage(id='cage_2', cage_no=2, cage_type='Food'), (0, 7): Cage(id='cage_2', cage_no=2, cage_type='Food'), (5, 5): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (6, 6): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (5, 6): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (6, 5): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (5, 7): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (7, 5): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (6, 4): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (4, 6): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (0, 0): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (8, 8): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (0, 8): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (8, 0): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (0, 9): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (9, 0): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (8, 1): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (1, 8): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (4, 4): Cage(id='cage_4', cage_no=4, cage_type='Food'), (9, 9): Cage(id='cage_4', cage_no=4, cage_type='Food'), (4, 9): Cage(id='cage_4', cage_no=4, cage_type='Food'), (9, 4): Cage(id='cage_4', cage_no=4, cage_type='Food'), (4, 8): Cage(id='cage_4', cage_no=4, cage_type='Food'), (8, 4): Cage(id='cage_4', cage_no=4, cage_type='Food'), (9, 5): Cage(id='cage_4', cage_no=4, cage_type='Food'), (5, 9): Cage(id='cage_4', cage_no=4, cage_type='Food')}))

## Store in the database

In [3]:
db_path = Path.cwd() / "ecohab.duckdb"
con = connect(db_path)
repo = DuckDBExperimentRepository(con)

if not repo.exists(experiment.name):
    repo.save(experiment, loader.layout_cfg)

repo.exists(experiment.name)

True

## Extract the experiment

In [4]:
loaded = repo.get(experiment.name, interpolate=True)
loaded

Experiment(name='DeepEcoHAB', start=datetime.datetime(2026, 6, 10, 11, 39, 24, 553118, tzinfo=<DstTzInfo 'Europe/Warsaw' CEST+2:00:00 DST>), end=None, light_start='07:00', dark_start='19:00', recording_timezone='Europe/Warsaw', animals={'EE1CEC1A': Animal(tag_no='EE1CEC1A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '6D68A819': Animal(tag_no='6D68A819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), 'DD43E61A': Animal(tag_no='DD43E61A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '3AFE9F1A': Animal(tag_no='3AFE9F1A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), 'D5969C1A': Animal(tag_no='D5969C1A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '0265E61A': Animal(tag_no='0265E61A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), 'F02AE61A': Animal(tag_no='F02AE61A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '12F5FF19': Animal(tag_no='12F5FF19', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort1_implant_worked_03_06_2026'), '3AE5FF19': Animal(tag_no='3AE5FF19', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort2_implant_worked_03_06_2026'), 'C8E2FF19': Animal(tag_no='C8E2FF19', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort2_implant_worked_03_06_2026'), 'C046E61A': Animal(tag_no='C046E61A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='Neurolux+', notes='Cohort2_implant_worked_03_06_2026'), 'F5EFFF19': Animal(tag_no='F5EFFF19', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'F273A819': Animal(tag_no='F273A819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'D71EA819': Animal(tag_no='D71EA819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'E967A819': Animal(tag_no='E967A819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'E6A59C1A': Animal(tag_no='E6A59C1A', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'A16CA819': Animal(tag_no='A16CA819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia'), 'F61EA819': Animal(tag_no='F61EA819', sex='Male', age={'age': '6', 'unit': 'months'}, dob=None, genetic_background=None, mouse_line=None, genotype='WT', treatment='No_implant', notes='No_implant_WT_C57_from_Ksenia')}, layout=Layout(cages={'cage_2': Cage(id='cage_2', cage_no=2, cage_type='Food'), 'cage_3': Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), 'cage_1': Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), 'cage_4': Cage(id='cage_4', cage_no=4, cage_type='Food')}, tunnels={'tunnel_1': Tunnel(id='tunnel_1', name='T1', endpoints=frozenset({'cage_1', 'cage_2'}), antennas={'cage_2': 1, 'cage_1': 0}, is_deadend=False), 'tunnel_2': Tunnel(id='tunnel_2', name='T2', endpoints=frozenset({'cage_3', 'cage_4'}), antennas={'cage_3': 5, 'cage_4': 4}, is_deadend=False), 'tunnel_3': Tunnel(id='tunnel_3', name='T3', endpoints=frozenset({'cage_2', 'cage_3'}), antennas={'cage_2': 7, 'cage_3': 6}, is_deadend=False), 'tunnel_4': Tunnel(id='tunnel_4', name='T4', endpoints=frozenset({'cage_1', 'cage_4'}), antennas={'cage_1': 8, 'cage_4': 9}, is_deadend=False)}, antennas={1: Antenna(id=1, tunnel_id='tunnel_1', cage_id='cage_2'), 0: Antenna(id=0, tunnel_id='tunnel_1', cage_id='cage_1'), 5: Antenna(id=5, tunnel_id='tunnel_2', cage_id='cage_3'), 4: Antenna(id=4, tunnel_id='tunnel_2', cage_id='cage_4'), 7: Antenna(id=7, tunnel_id='tunnel_3', cage_id='cage_2'), 6: Antenna(id=6, tunnel_id='tunnel_3', cage_id='cage_3'), 8: Antenna(id=8, tunnel_id='tunnel_4', cage_id='cage_1'), 9: Antenna(id=9, tunnel_id='tunnel_4', cage_id='cage_4')}, _pairs={(1, 0): Crossing(tunnel_id='tunnel_1', from_cage_id='cage_2', to_cage_id='cage_1'), (0, 1): Crossing(tunnel_id='tunnel_1', from_cage_id='cage_1', to_cage_id='cage_2'), (5, 4): Crossing(tunnel_id='tunnel_2', from_cage_id='cage_3', to_cage_id='cage_4'), (4, 5): Crossing(tunnel_id='tunnel_2', from_cage_id='cage_4', to_cage_id='cage_3'), (7, 6): Crossing(tunnel_id='tunnel_3', from_cage_id='cage_2', to_cage_id='cage_3'), (6, 7): Crossing(tunnel_id='tunnel_3', from_cage_id='cage_3', to_cage_id='cage_2'), (8, 9): Crossing(tunnel_id='tunnel_4', from_cage_id='cage_1', to_cage_id='cage_4'), (9, 8): Crossing(tunnel_id='tunnel_4', from_cage_id='cage_4', to_cage_id='cage_1'), (1, 1): Cage(id='cage_2', cage_no=2, cage_type='Food'), (7, 7): Cage(id='cage_2', cage_no=2, cage_type='Food'), (1, 7): Cage(id='cage_2', cage_no=2, cage_type='Food'), (7, 1): Cage(id='cage_2', cage_no=2, cage_type='Food'), (1, 6): Cage(id='cage_2', cage_no=2, cage_type='Food'), (6, 1): Cage(id='cage_2', cage_no=2, cage_type='Food'), (7, 0): Cage(id='cage_2', cage_no=2, cage_type='Food'), (0, 7): Cage(id='cage_2', cage_no=2, cage_type='Food'), (5, 5): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (6, 6): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (5, 6): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (6, 5): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (5, 7): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (7, 5): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (6, 4): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (4, 6): Cage(id='cage_3', cage_no=3, cage_type='Stimulus'), (0, 0): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (8, 8): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (0, 8): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (8, 0): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (0, 9): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (9, 0): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (8, 1): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (1, 8): Cage(id='cage_1', cage_no=1, cage_type='Stimulus'), (4, 4): Cage(id='cage_4', cage_no=4, cage_type='Food'), (9, 9): Cage(id='cage_4', cage_no=4, cage_type='Food'), (4, 9): Cage(id='cage_4', cage_no=4, cage_type='Food'), (9, 4): Cage(id='cage_4', cage_no=4, cage_type='Food'), (4, 8): Cage(id='cage_4', cage_no=4, cage_type='Food'), (8, 4): Cage(id='cage_4', cage_no=4, cage_type='Food'), (9, 5): Cage(id='cage_4', cage_no=4, cage_type='Food'), (5, 9): Cage(id='cage_4', cage_no=4, cage_type='Food')}))

## Extract animals

In [5]:
pl.DataFrame([
    {
        "tag_no": a.tag_no, "sex": a.sex, "genotype": a.genotype, "treatment": a.treatment,
        "genetic_background": a.genetic_background, "mouse_line": a.mouse_line,
        "age_value": (a.age or {}).get("age"), "age_unit": (a.age or {}).get("unit"),
        "dob": a.dob, "notes": a.notes,
    }
    for a in loaded.animals.values()
])

shape: (18, 10)
┌──────────┬──────┬──────────┬────────────┬───┬───────────┬──────────┬──────┬──────────────────────┐
│ tag_no   ┆ sex  ┆ genotype ┆ treatment  ┆ … ┆ age_value ┆ age_unit ┆ dob  ┆ notes                │
│ ---      ┆ ---  ┆ ---      ┆ ---        ┆   ┆ ---       ┆ ---      ┆ ---  ┆ ---                  │
│ str      ┆ str  ┆ str      ┆ str        ┆   ┆ str       ┆ str      ┆ null ┆ str                  │
╞══════════╪══════╪══════════╪════════════╪═══╪═══════════╪══════════╪══════╪══════════════════════╡
│ EE1CEC1A ┆ Male ┆ WT       ┆ Neurolux+  ┆ … ┆ 6         ┆ months   ┆ null ┆ Cohort1_implant_work │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ ed_03_06_2…          │
│ 6D68A819 ┆ Male ┆ WT       ┆ Neurolux+  ┆ … ┆ 6         ┆ months   ┆ null ┆ Cohort1_implant_work │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ ed_03_06_2…          │
│ DD43E61A ┆ Male ┆ WT       ┆ Neurolux+  ┆ … ┆ 6         ┆ months   ┆ null ┆ Cohort1_implant_work │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ ed_03_06_2…          │
│ 3AFE9F1A ┆ Male ┆ WT       ┆ Neurolux+  ┆ … ┆ 6         ┆ months   ┆ null ┆ Cohort1_implant_work │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ ed_03_06_2…          │
│ D5969C1A ┆ Male ┆ WT       ┆ Neurolux+  ┆ … ┆ 6         ┆ months   ┆ null ┆ Cohort1_implant_work │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ ed_03_06_2…          │
│ …        ┆ …    ┆ …        ┆ …          ┆ … ┆ …         ┆ …        ┆ …    ┆ …                    │
│ D71EA819 ┆ Male ┆ WT       ┆ No_implant ┆ … ┆ 6         ┆ months   ┆ null ┆ No_implant_WT_C57_fr │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ om_Ksenia            │
│ E967A819 ┆ Male ┆ WT       ┆ No_implant ┆ … ┆ 6         ┆ months   ┆ null ┆ No_implant_WT_C57_fr │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ om_Ksenia            │
│ E6A59C1A ┆ Male ┆ WT       ┆ No_implant ┆ … ┆ 6         ┆ months   ┆ null ┆ No_implant_WT_C57_fr │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ om_Ksenia            │
│ A16CA819 ┆ Male ┆ WT       ┆ No_implant ┆ … ┆ 6         ┆ months   ┆ null ┆ No_implant_WT_C57_fr │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ om_Ksenia            │
│ F61EA819 ┆ Male ┆ WT       ┆ No_implant ┆ … ┆ 6         ┆ months   ┆ null ┆ No_implant_WT_C57_fr │
│          ┆      ┆          ┆            ┆   ┆           ┆          ┆      ┆ om_Ksenia            │
└──────────┴──────┴──────────┴────────────┴───┴───────────┴──────────┴──────┴──────────────────────┘

## Extract cages

In [6]:
loaded.layout.to_dimension_frames()["cages"]

shape: (4, 3)
┌─────────┬─────────┬───────────┐
│ cage_id ┆ cage_no ┆ cage_type │
│ ---     ┆ ---     ┆ ---       │
│ str     ┆ i64     ┆ str       │
╞═════════╪═════════╪═══════════╡
│ cage_1  ┆ 1       ┆ Stimulus  │
│ cage_2  ┆ 2       ┆ Food      │
│ cage_3  ┆ 3       ┆ Stimulus  │
│ cage_4  ┆ 4       ┆ Food      │
└─────────┴─────────┴───────────┘

## Extract interpolation data

The layout resolves every observed antenna pair to either a `Cage` (animal stayed in place) or a `Crossing` (animal moved between cages through a tunnel). This pair → location map is what `interpolate=True` widens: reads that skip an antenna are filled in using it.

In [7]:
def describe_pair(target):
    if isinstance(target, Cage):
        return "cage", target.id, None
    return "crossing", None, target.tunnel_id

rows = []
for (a_from, a_to), target in sorted(loaded.layout.pairs.items()):
    kind, cage_id, tunnel_id = describe_pair(target)
    rows.append({
        "antenna_from": a_from, "antenna_to": a_to, "kind": kind,
        "cage_id": cage_id, "tunnel_id": tunnel_id,
    })

pl.DataFrame(rows)

shape: (40, 5)
┌──────────────┬────────────┬──────────┬─────────┬───────────┐
│ antenna_from ┆ antenna_to ┆ kind     ┆ cage_id ┆ tunnel_id │
│ ---          ┆ ---        ┆ ---      ┆ ---     ┆ ---       │
│ i64          ┆ i64        ┆ str      ┆ str     ┆ str       │
╞══════════════╪════════════╪══════════╪═════════╪═══════════╡
│ 0            ┆ 0          ┆ cage     ┆ cage_1  ┆ null      │
│ 0            ┆ 1          ┆ crossing ┆ null    ┆ tunnel_1  │
│ 0            ┆ 7          ┆ cage     ┆ cage_2  ┆ null      │
│ 0            ┆ 8          ┆ cage     ┆ cage_1  ┆ null      │
│ 0            ┆ 9          ┆ cage     ┆ cage_1  ┆ null      │
│ …            ┆ …          ┆ …        ┆ …       ┆ …         │
│ 9            ┆ 0          ┆ cage     ┆ cage_1  ┆ null      │
│ 9            ┆ 4          ┆ cage     ┆ cage_4  ┆ null      │
│ 9            ┆ 5          ┆ cage     ┆ cage_4  ┆ null      │
│ 9            ┆ 8          ┆ crossing ┆ null    ┆ tunnel_4  │
│ 9            ┆ 9          ┆ cage     ┆ cage_4  ┆ null      │
└──────────────┴────────────┴──────────┴─────────┴───────────┘

### Interpolated vs. raw antenna pairs

In [8]:
raw_layout = loader.load_layout(interpolate=False)
print(f"raw antenna pairs: {len(raw_layout.pairs)}")
print(f"interpolated antenna pairs: {len(loaded.layout.pairs)}")

raw antenna pairs: 24
interpolated antenna pairs: 40